# Generated by Django 4.2.4 on 2023-09-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, null=True)),
                ('country_code', models.IntegerField(null=True)),
                ('country_description', models.CharField(max_length=200, null=True)),
                ('popular_cities', models.CharField(max_length=100, null=True, unique=True)),
                ('education_rating', models.IntegerField(null=True)),
                ('image_url', models.URLField(max_length=500)),
            ],
        ),
    ]
